[package]
name = "bil_row_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.9.0"
tokio = { version = "1", features = ["full"] }
chashmap = "2.2.2"
